/*
 * gpio.c
 *
 *  Created on: Jul 8, 2020
 *      Author: Abdelaziz Sayed
 */


#include "gpio.h"


void GPIO_Init(void)
{

   SET_PIN_DIRECTION(HEATER_DIRECTION,HEATER_PIN,OUTPUT);
   SET_PIN_DIRECTION(COOLER_DIRECTION,COOLER_PIN,OUTPUT);
   SET_PIN_DIRECTION(LED_DIRECTION,LED_PIN,OUTPUT);
   SET_PIN_DIRECTION(DIGIT1_DIRECTION,DIGIT1_PIN,OUTPUT);
   SET_PIN_DIRECTION(DIGIT2_DIRECTION,DIGIT2_PIN,OUTPUT);
   SET_PIN_DIRECTION(DOWN_BUTTON_DIRECTION,DOWN_BUTTON_PIN,INPUT);
   SET_PIN_DIRECTION(UP_BUTTON_DIRECTION,UP_BUTTON_PIN,INPUT);
   SET_PIN_DIRECTION(ON_OFF_BUTTON_DIRECTION,ON_OFF_BUTTON_PIN,INPUT);
   SET_PIN_DIRECTION(TEMPERATURE_SENSOR_DIRECTION,TEMPERATURE_SENSOR_PIN,INPUT);
   SET_PIN_DIRECTION(EEPROM_SCK_DIRECTION,EEPROM_SCK_PIN,OUTPUT);
   SET_PIN_DIRECTION(EEPROM_SDA_DIRECTION,EEPROM_SDA_PIN,INPUT);
   SET_PORT_DIRECTION(_7SEGMENT_DIRECTION,OUTPUT);
   
 
    
    

}



